MundoDeDonas/Controllers/HomeController.cs
using SendGrid;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Entidades = MundoDeDonas.Models.Entidades;
using System.Web.Mvc;
using SendGrid.Helpers.Mail;
using System.Threading.Tasks;

namespace MundoDeDonas.Controllers {
    public class HomeController : Controller {
        public ActionResult Index() {
            return View();
        }

        public ActionResult About() {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact() {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public async Task<ActionResult> TienesAntojo() {
            var apiKey = "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";
            var sTempleteID = "d-81501a793bbb4f8db1099454f1f4fb57";
            var oClient = new SendGridClient(apiKey);
            var oFrom = new EmailAddress("18240248@leon.tecnm.mx", "Mundo De donas");
            var oSubject = "";
            var oTo = new EmailAddress("hernandezpadillaemilioemmanuel@gmail.com");
            var oMailHelper = MailHelper.CreateSingleTemplateEmail(oFrom, oTo, sTempleteID, null);

            var r = await oClient.SendEmailAsync(oMailHelper);
            if (!r.IsSuccessStatusCode)
                return View();
            return View("Index"); 
        }

        //public async Task<ActionResult> TienesAntojo(Entidades.Usuario oUsuario) {
        //    var apiKey = "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";
        //    var sTempleteID = "d-81501a793bbb4f8db1099454f1f4fb57";
        //    var oClient = new SendGridClient(apiKey);
        //    var oFrom = new EmailAddress("bboylio05@gmail.com", "Mundo De donas");
        //    var oSubject = "";
        //    var oTo = new EmailAddress("hernandezpadillaemilioemmanuel@gmail.com");
        //    var oMailHelper = MailHelper.CreateSingleTemplateEmail(oFrom,oTo, sTempleteID,null);

        //    var r = await oClient.SendEmailAsync(oMailHelper);
        //    if (!r.IsSuccessStatusCode)
        //        return View();
        //    return View("Index");
        //}
    }
}

MundoDeDonas/Controllers/Pedido_Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Entidades = MundoDeDonas.Models.Entidades;
using Datos = MundoDeDonas.Models.Datos;
using System.Web.Mvc;
using System.IO;

namespace MundoDeDonas.Controllers {
    public class Pedido_Controller : Controller {
        // GET: Pedido_
        public ActionResult Pedido() {
            return View();
        }

        public JsonResult RealizarPedido(FormCollection form) {
            var oDPedido = new Datos.Pedido();
            var oEPedido = new Entidades.Pedido();
            var oDIngrediente = new Datos.Pedido_Ingrediente();
            var oEIngrediente = new Entidades.Pedido_Ingrediente();
            var oEIngredientes = new Entidades.Pedido_Ingredientes();

            string method = form["payment-method-checker"].ToString();
            string num_tarjeta = form["num_tarjeta"].ToString();
            string fecha_venc = form["fecha_venc"].ToString();
            string titular = form["titular"].ToString();
            string ccv = form["ccv"].ToString();
            int cantidad = Convert.ToInt32(form["cantidad"]);
            int cover_option = Convert.ToInt32(form["cover-option"]);
            int glass_option = Convert.ToInt32(form["glass-option"]);
            int fill_option = Convert.ToInt32(form["fill-option"]);

            try {
                if(/*false*/System.Web.HttpContext.Current.Session["Id"] == null) {
                    //return View("Login", "Usuario_");
                    return Json(new { result = false, message = "No ha iniciado sesión" }, JsonRequestBehavior.AllowGet);
                } else {
                    oEPedido.Decenas = cantidad;
                    oEPedido.MetodoPago = (method == "cash") ? 1 : (method == "credit") ? 2 : 0;
                    oEPedido.IdUsuario = /*1;*/ (int) System.Web.HttpContext.Current.Session["Id"];
                    var lastID = oDPedido.Add(oEPedido);
                    oEIngrediente.IdPedido = lastID;
                    oEIngrediente.Ingrediente = cover_option;
                    oEIngredientes.Add(oEIngrediente);
                    oEIngrediente = new Entidades.Pedido_Ingrediente();
                    oEIngrediente.IdPedido = lastID;
                    oEIngrediente.Ingrediente = glass_option;
                    oEIngredientes.Add(oEIngrediente);
                    oEIngrediente = new Entidades.Pedido_Ingrediente();
                    oEIngrediente.IdPedido = lastID;
                    oEIngrediente.Ingrediente = fill_option;
                    oEIngredientes.Add(oEIngrediente);
                    foreach (Entidades.Pedido_Ingrediente ingrediente in oEIngredientes) {
                        oDIngrediente.Add(ingrediente);

                    }
                    return Json(new { result = true }, JsonRequestBehavior.AllowGet);
                }
            } catch(Exception e) {
                using(StreamWriter writer = new StreamWriter(Server.MapPath("/log.txt"))) {
                    writer.WriteLine("----------------" + e.Message);
                }
                return Json(new { result = false, message = e.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

MundoDeDonas/Controllers/Usuario_Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Entidades = MundoDeDonas.Models.Entidades;
using Datos = MundoDeDonas.Models.Datos;
using System.Web.Mvc;
using SendGrid;
using SendGrid.Helpers.Mail;

namespace MundoDeDonas.Controllers {
    public class Usuario_Controller : Controller {
        public ActionResult RegistrarUsuario() {
            return View();
        }

        [System.Web.Mvc.HttpPost]
        [System.Web.Mvc.AllowAnonymous]
        public ActionResult RegistrarUsuario(Entidades.Usuario oUsuario) {
            var oDUsuario = new Datos.Usuario();
            var apiKey = "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";
            var sTempleteID = "d-81501a793bbb4f8db1099454f1f4fb57";
            var oClient = new SendGridClient(apiKey);
            var oFrom = new EmailAddress("18240248@leon.tecnm.mx", "Mundo De donas");
            var oTo = new EmailAddress(oUsuario.Email);
            var oMailHelper = MailHelper.CreateSingleTemplateEmail(oFrom, oTo, sTempleteID, null);

            oClient.SendEmailAsync(oMailHelper);
            oUsuario.FechaRegistro = DateTime.Today;
            oDUsuario.Add(oUsuario);
            System.Web.HttpContext.Current.Session["Nombre"] = oUsuario.Nombre;
            System.Web.HttpContext.Current.Session["Email"] = oUsuario.Email;
            System.Web.HttpContext.Current.Session["Id"] = oDUsuario.VerificaLogin(oUsuario.Email, oUsuario.Contrasenia).Id;
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Login() {
            return View();
        }

        [System.Web.Mvc.HttpPost]
        [System.Web.Mvc.AllowAnonymous]
        public ActionResult Login(Entidades.Usuario oUsuario) {
            Datos.Usuario oDUsuario = new Datos.Usuario();

            try {
                oUsuario = oDUsuario.VerificaLogin(oUsuario.Email, oUsuario.Contrasenia);
                if (oUsuario == null) {
                    return View();
                } else {
                    System.Web.HttpContext.Current.Session["Nombre"] = oUsuario.Nombre;
                    System.Web.HttpContext.Current.Session["Email"] = oUsuario.Email;
                    System.Web.HttpContext.Current.Session["Id"] = oUsuario.Id;
                    return RedirectToAction("Index", "Home");
                }
            } catch (Exception ex) {
                return View();
            }
        }

        public ActionResult Logout() {
            if (System.Web.HttpContext.Current.Session["Id"] != null) 
                System.Web.HttpContext.Current.Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        public JsonResult ObtenerUsuario(int clave) {
            var oUsuario = new Entidades.Usuario();
            var oDUsuario = new Datos.Usuario();
            oUsuario = oDUsuario.GetOne(clave);
            return new JsonResult() { Data = oUsuario, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

    }
}

MundoDeDonas/Views/Home/About.cshtml
@{
    string sName = "";

    if (System.Web.HttpContext.Current.Session["Id"] == null) {
        sName = "Login";
    } else {
        sName = (string)System.Web.HttpContext.Current.Session["Nombre"];
    }
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Quienes somos</title>
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sacramento">
    <link rel="stylesheet" href="~/assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="~/assets/css/custom-radio.css">
    <link rel="stylesheet" href="~/assets/css/Navigation-Clean.css">
    <link rel="stylesheet" href="~/assets/css/styles.css">
    <link rel="icon" type="image/png" sizes="32x32" href="~/assets/img/favicon-32x32.png">
</head>

<body style="background: url('/assets/img/background-image.png'), #ffffff;padding-top: -823px ;">
    <nav class="navbar navbar-light navbar-expand-md text-right navigation-clean" style="background: #ffdbec;box-shadow: 0px 3px 7px rgba(0,0,0,0.13);">
        <div class="container">
            <a class="navbar-brand" href="#">
                <div class="logo-image"></div>
            </a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item">@Html.ActionLink("Inicio", "Index", "Home", null, new { @class = "nav-link active", style = "font-family: Lobster, cursive;color: rgb(125,9,101);" })</li>
                    @*<a >inicio</a>*@
                    <li class="nav-item">@Html.ActionLink("Crea tu Dona", "Pedido", "Pedido_", null, new { @class = "nav-link", style = "font-family: Lobster, cursive; color: rgb(125,9,101);" })</li>
                    @*<a  href="crea.html">crea tu dona</a>*@
                    <li class="nav-item">@Html.ActionLink("¿Quienes Somos?", "About", "Home", null, new { @class = "nav-link", style = "font-family: Lobster, cursive;color: rgb(125,9,101);" })</li>
                    <li class="nav-item dropdown" style="font-family: Lobster, cursive;">
                        <a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#" style="color: rgb(125,9,101);">@sName</a>
                        <div class="dropdown-menu" style="box-shadow: 2px 2px 6px rgba(0,0,0,0.16);">
                            @{if (System.Web.HttpContext.Current.Session["Id"] == null) {
                                    @Html.ActionLink("Login", "Login", "Usuario_", null, new { @class = "dropdown-item" })
                                    @Html.ActionLink("Sign in", "RegistrarUsuario", "Usuario_", null, new { @class = "dropdown-item" })
                                } else {
                                    @Html.ActionLink("Logout", "Logout", "Usuario_", null, new { @class = "dropdown-item" })
                                }
                            }
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div style="background: url('/assets/img/about-stuff/title.png');
        height: 220px;"></div>
    <div style="display: flex;padding: 50px;">
        <div style="background: #ffffff;padding: 50px;">
            <div style="margin-bottom: 10px;"><span style="color: #8f8f8f;font-size: 54px;font-family: Sacramento, cursive;font-weight: normal;">Nos encantan los postres...</span></div>
            <div>
                <p>
                    En 2020 nos surge la idea de que las personas hoy en día necesitan alimentos que se amolden a lo que ellos desean, que ellos puedan crear y personalizar lo que van a degustar. Es así como nace nuestro proyecto Donuts &amp; Donuts. Donas
                    que el usuario podrá personalizar a su gusto y que serán entregadas en la comodidad de su hogar. Hechas con ingredientes de la más alta calidad y decoradas artesanalmente preparadas al momento por lo cual la frescura es garantía. Mas
                    que una dona somo una experiencia.<br><br>
                </p>
            </div>
            <div style="font-size: 23px;display: flex;justify-content: space-between;margin-right: auto;margin-left: auto;width: 400px;">
                <span class="d-xl-flex align-items-xl-end">Siguenos en&nbsp;</span><i class="fa fa-facebook-square" style="font-size: 70px;color: #0022ff;"></i><i class="fa fa-instagram" style="font-size: 70px;color: #ff0068;"></i><i class="fa fa-twitter"
                                                                                                                                                                                                                                          style="font-size: 70px;color: #0099ff;"></i>
            </div>
        </div>
        <div style="margin-left: -220px;margin-top: 97px;"><img src="/assets/img/about-stuff/au-friends2.png"></div>
    </div>
    <script src="~/assets/js/jquery.min.js"></script>
    <script src="~/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/assets/js/make-script.js"></script>
</body>

</html>

MundoDeDonas/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MundoDeDonas/Views/Home/Index.cshtml
@{
    string sName = "";

    if (System.Web.HttpContext.Current.Session["Id"] == null) {
        sName = "Login";
    } else {
        sName = (string)System.Web.HttpContext.Current.Session["Nombre"];
    }
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Donuts&amp;Donuts - Inicio</title>
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sacramento">
    <link rel="stylesheet" href="~/assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="~/assets/css/custom-radio.css">
    <link rel="stylesheet" href="~/assets/css/Navigation-Clean.css">
    <link rel="stylesheet" href="~/assets/css/styles.css">
    <link rel="icon" type="image/png" sizes="32x32" href="~/assets/img/favicon-32x32.png">
</head>

<body style="        background: url(&quot;~/assets/img/background-image.png&quot;) top / auto;">
    <nav class="navbar navbar-light navbar-expand-md text-right navigation-clean" style="background: #ffdbec;box-shadow: 0px 3px 7px rgba(0,0,0,0.13);">
        <div class="container">
            <a class="navbar-brand" href="#">
                <div class="logo-image"></div>
            </a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item">@Html.ActionLink("Inicio", "Index", "Home", null, new { @class = "nav-link active", style = "font-family: Lobster, cursive;color: rgb(125,9,101);" })</li>
                    <li class="nav-item">@Html.ActionLink("Crea tu Dona", "Pedido", "Pedido_", null, new { @class = "nav-link", style = "font-family: Lobster, cursive;color: rgb(125,9,101);" })</li>
                    <li class="nav-item" style="font-family: Lobster, cursive;">@Html.ActionLink("¿Quienes Somos?", "About", "Home", null, new { @class = "nav-link", style = "font-family: Lobster, cursive;color: rgb(125,9,101);" })</li> @*<a class="nav-link" href="~/Views/Home/About.cshtml" style="font-family: Lobster, cursive;color: rgb(125,9,101);">¿quiénes somos?</a>*@
                    <li class="nav-item dropdown">
                        <a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#" style="font-family: Lobster, cursive; color: rgb(125,9,101);">@sName</a>
                        <div class="dropdown-menu" style="box-shadow: 2px 2px 6px rgba(0,0,0,0.16);">
                            @{if (System.Web.HttpContext.Current.Session["Id"] == null) {
                                    @Html.ActionLink("Login", "Login", "Usuario_", null, new { @class = "dropdown-item" })
                                    @Html.ActionLink("Sign in", "RegistrarUsuario", "Usuario_", null, new { @class = "dropdown-item" })
                                } else {
                                    @*@Html.ActionLink("Invitar Amigo", "TienesAntojo", "Home", null, new { @class = "dropdown-item" })*@
                                    @Html.ActionLink("Logout", "Logout", "Usuario_", null, new { @class = "dropdown-item" })
                                }
                            }
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="banner"></div>
    <div class="section-one">
        <div class="section-one-text">
            <p style="font-family: 'Open Sans', sans-serif;color: rgb(255,255,255);width: 550px;">En 2020 nos surge la idea de que las personas hoy en día necesitan alimentos que se amolden a lo que ellos desean, que ellos puedan crear y personalizar lo que van a degustar. Es así como nace nuestro proyecto Donuts &amp; Donuts. </p>
        </div>
    </div>
    <div class="section-two">
        <div class="section-two-text">
            <p style="width: 739px;text-align: justify;">
                Donas que el usuario podrá personalizar a su gusto y que serán entregadas en la comodidad de su hogar. Hechas con ingredientes de la más alta calidad y decoradas artesanalmente preparadas al momento por lo cual la frescura es garantía.<br>&nbsp;<br>Mas
                que una dona somo una experiencia.
            </p>
        </div><img src="/assets/img/index-stuff/donas-cascade.png" style="height: 820px;margin-top: -200px;margin-left: -30px;">
    </div>
    <footer class="footer">
        <div class="footer-logo-container"><img src="/assets/img/logo.png" style="position: absolute;top: -50px;width: 120px;"><img src="/assets/img/index-stuff/logo-1.png" style="position: absolute;top: 15px;left: -40px;"></div>
    </footer>
    <script src="~/assets/js/jquery.min.js"></script>
    <script src="~/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/assets/js/make-script.js"></script>
</body>

</html>